### ISSUE TITLE
Installation Failure in “Run ./install_frontend.sh“

### ISSUE THREAD

**Issue by linqingfeng** [FarmBot/farmbot-web-frontend#155] opened 2016-11-14 02:56 UTC
Hi,

We try to install "Run ./install_frontend.sh"

But the following error:

ts-loader: Using typescript@2.0.9 and /tmp/farmbot_frontend/tsconfig.json
Hash: a7883aa04607000db45a
Version: webpack 1.13.3
Time: 104144ms
                       Asset       Size  Chunks             Chunk Names
                app-index.js    18.3 kB       0  [emitted]  app-index
     app-resources/bundle.js     977 kB       1  [emitted]  app-resources/bundle
              splash-page.js    18.4 kB       2  [emitted]  splash-page
    app-resources/styles.css    25.9 kB       1  [emitted]  app-resources/bundle
            app-index.js.map     245 kB       0  [emitted]  app-index
 app-resources/bundle.js.map    7.72 MB       1  [emitted]  app-resources/bundle
app-resources/styles.css.map  101 bytes       1  [emitted]  app-resources/bundle
          splash-page.js.map     245 kB       2  [emitted]  splash-page
                  index.html    3.24 kB          [emitted]
              app/index.html  486 bytes          [emitted]
   [1] ./src/static ^\.\/.*\.hbs$ 202 bytes {0} {2} [built]
 [674] ./public/app-resources/languages ^\.\/.*\.js$ 172 bytes {1} [built]
 [675] ./public/app-resources/languages/en.js 173 bytes {1} [optional] [built]
    + 675 hidden modules

ERROR in /tmp/farmbot_frontend/node_modules/moment/moment.d.ts
(63,5): error TS2411: Property 'sameDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in /tmp/farmbot_frontend/node_modules/moment/moment.d.ts
(64,5): error TS2411: Property 'nextDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in /tmp/farmbot_frontend/node_modules/moment/moment.d.ts
(65,5): error TS2411: Property 'lastDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in /tmp/farmbot_frontend/node_modules/moment/moment.d.ts
(66,5): error TS2411: Property 'nextWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in /tmp/farmbot_frontend/node_modules/moment/moment.d.ts
(67,5): error TS2411: Property 'lastWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.

ERROR in /tmp/farmbot_frontend/node_modules/moment/moment.d.ts
(68,5): error TS2411: Property 'sameElse' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.
Child extract-text-webpack-plugin:
        + 2 hidden modules

How to solve? thank you very much!

**Comment by RickCarlino** [comment] 2016-11-14 15:58
@linqingfeng Thanks for bringing this to our attention. We are seeing the issue this morning also.

It appears to be a version mismatch between `momentjs` and the typescript typings. I will update this thread when I find the solution.

**Comment by RickCarlino** [comment] 2016-11-14 16:11
Ok - I think I have isolated the issue. The error messages you're seeing should not stop you from deploying the server, and they should go away when I merge the fix into master (next 24 hours).

It is most likely caused by the version of moment.js listed in the `package.json` file. You can change the version to `2.15.2` if you need a temporary fix. Otherwise, it should be fixed shortly and not interfere with the build process.

**Closed** 2016-11-14 16:19 UTC

**Comment by linqingfeng** [comment] 2016-11-15 01:37
Hi,

Thank you for fixing these bugs, but when we build with the latest version, we get an error:

ts-loader: Using typescript@2.0.9 and /tmp/farmbot_frontend/tsconfig.json
Hash: 3e695a9d15219e77f699
Version: webpack 1.13.3
Time: 124700ms
                       Asset       Size  Chunks             Chunk Names
                app-index.js    14.5 kB       0  [emitted]  app-index
     app-resources/bundle.js     973 kB       1  [emitted]  app-resources/bundle
               front_page.js     359 kB       2  [emitted]  front_page
    app-resources/styles.css    25.9 kB    1, 2  [emitted]  app-resources/bundle, front_page
            app-index.js.map     234 kB       0  [emitted]  app-index
 app-resources/bundle.js.map    7.79 MB       1  [emitted]  app-resources/bundle
app-resources/styles.css.map  101 bytes    1, 2  [emitted]  app-resources/bundle, front_page
           front_page.js.map    3.79 MB       2  [emitted]  front_page
              app/index.html  486 bytes          [emitted]
   [1] ./src/static ^\.\/.*\.hbs$ 180 bytes {0} [built]
 [669] ./public/app-resources/languages ^\.\/.*\.js$ 172 bytes {1} {2} [built]
 [670] ./public/app-resources/languages/en.js 173 bytes {1} {2} [optional] [built]
    + 671 hidden modules

ERROR in /tmp/farmbot_frontend/node_modules/@types/mqtt/node_modules/@types/node/index.d.ts
(73,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequireFunction', but here has type 'NodeRequire'.
Child extract-text-webpack-plugin:
        + 2 hidden modules

**Comment by linqingfeng** [comment] 2016-11-15 02:05
Hi,

We try to modify it
/tmp/farmbot_frontend/node_modules/@types/mqtt/node_modules/@types/node/index.d.ts

`declare var require: NodeRequireFunction;
//declare var require: NodeRequire;`

This will be able to build a successful, this will not be a problem?
Thank you very much.

**Comment by RickCarlino** [comment] 2016-11-15 14:49
@linqingfeng It will not affect the app, but it is inconvenient to look at.

Can you try re-running the `install_frontend.sh` again and let me know if the errors still appear?

I think this is happening because of different NPM versions between my machine and yours (I do not see the error locally, but users are reporting it). I added an `npm-shrinkwrap.json` file to the repo which will hopefully fix the problem.

**Comment by linqingfeng** [comment] 2016-11-16 17:08
@RickCarlino Thanks,we re-use the latest version of the building, the problem has been fixed, very grateful!

**Comment by RickCarlino** [comment] 2016-11-16 18:21
@linqingfeng Great! As a side note: The front page login screen is still malfunctioning (we're investigating right now). Please use `/api/login` for now.
