### ISSUE TITLE
Cannot set length

### ISSUE THREAD

**Issue by menghong777** [FarmBot/farmbot-web-frontend#188] opened 2017-02-24 08:08 UTC
# Expected Behavior
Able to set X, Y and Z length in device page.
# Actual Behavior
It shows "---" in the form and unable to save.
# Steps to Reproduce
For example: We put value 1 into length field and it won't save for X, Y, Z axis.

@joevo2
P/s: We are currently using RPi 3 with 3.0.5 version software and version 1 for Arduino firmware.

**Comment by joevo2** [comment] 2017-02-24 12:43
We are suspecting because that we could not set the length of the farmbot that are causing the farmbot not moving at all, only "tick tick" sound in the stepper motors :(

**Comment by RickCarlino** [comment] 2017-04-28 12:45
This was fixed in this week's deploy. Feel free to re-open if you need help or clarification.

**Comment by RickCarlino** [comment] 2017-04-28 12:45
Whoops - got my issues mixed up. Please disregard previous comment, as it was intended for a different issue. We're still working on this one.

**Closed** 2017-06-22 13:23 UTC
